import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import TanStackQueryProvider from '@/provider/query/tanstack.provider';
import { Toaster } from 'react-hot-toast';

const font = Roboto({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <TanStackQueryProvider>
          {children} <Toaster position="bottom-center" reverseOrder={false} />
        </TanStackQueryProvider>
      </body>
    </html>
  );
}
