services:
  site:
    build: .
    #    command: ['npm', 'run', 'start:docker']
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    volumes:
      - .:/home/node/app
    external_links:
      - 'host.docker.internal'
    depends_on:
      - api

  api:
    image: ghcr.io/samuel-ricardo/tutorialls_api:main
    #restart: always
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    external_links:
      - 'host.docker.internal'

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    external_links:
      - 'host.docker.internal'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    external_links:
      - 'host.docker.internal'

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tutorialls_database
    volumes:
      - ./.docker/data/db:/var/lib/postgresql/data
    external_links:
      - 'host.docker.internal'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./.docker/data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    external_links:
      - 'host.docker.internal'
